version: "3.7"

services:
    api:
        image: ghcr.io/htchan/web-history:api-latest
        deploy:
            resources:
                limits:
                    memory: '100M'
        hostname: webhistory_backend
        volumes:
            - ./bin/database:/database
            - ./bin/logs:/logs
            - ./database/migrations:/migrations
            - ./data/config:/config
        networks:
            - router
            - database
            - k3d-development
        profiles:
            - all
            - api
            - web
        ports:
            - 9105:9105
        env_file:
            - ./data/env/.env.backend.docker

    worker:
        image: ghcr.io/htchan/web-history:worker-latest
        deploy:
            resources:
                limits:
                    memory: '25M'
        hostname: webhistory_worker
        volumes:
            - ./bin/database:/database
            - ./bin/logs:/logs
            - ./database/migrations:/migrations
            - ./data/config:/config
        networks:
            - database
            - trace
            - k3d-development
        profiles:
            - all
            - worker
        env_file:
            - ./data/env/.env.worker.docker

    backup:
        build:
            context: ./backup
            dockerfile: ./Dockerfile
        volumes:
            - ./bin/backup:/backup
        networks:
            - database
        profiles:
            - all
            - backup
        env_file:
            - ./.env

volumes:
    frontend_volume:
        name: webhistory_frontend_volume

networks:
    router:
        driver: bridge
        name: router
    database:
        name: database
        external: true
    trace:
        name: trace
        external: true
    k3d-development:
        external: true
        name: k3d-development
