version: "3.7"

services:
    backend:
        build: 
            context: ./backend
            dockerfile: ./build/Dockerfile.backend
        volumes:
            - ./bin/database:/database
            - ./backend/assets/api_parser:/api_parser
            - /etc/timezone:/etc/timezone/ro
        networks:
            - router
        profiles:
            - all
            - backend
            - web
        env_file:
            - ./backend/assets/.env.backend
        command: sh -c "./backend"

    batch:
        build:
            context: ./backend
            dockerfile: ./build/Dockerfile.batch
        deploy:
            resources:
                limits:
                    memory: '20M'
        volumes:
            - ./bin/database:/database
            - ./bin/logs:/logs
            - ./backend/assets/api_parser:/api_parser
            - /etc/timezone:/etc/timezone:ro
        networks:
            - router
        profiles:
            - all
            - batch
        command: sh -c "crond && tail -f /dev/null"


    frontend:
        image: "flutter:latest"
        volumes:
            - frontend_volume:/build/web
            - ./frontend/src:/usr/src/app
        networks:
            - router
        profiles:
            - all
            - frontend
            - web
        command: sh -c "flutter --version ; flutter pub get ; flutter build web"

volumes:
    frontend_volume:
        name: webhistory_frontend_volume

networks:
    router:
        driver: bridge
        name: router
