
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: web-watcher.migrations-claim # Sets name of PV
  labels:
    project: web-watcher
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany # Sets read and write access
  resources:
    requests:
      storage: 100Mi # Sets volume size
  volumeName: web-watcher.migrations-volume
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: web-watcher.config-claim # Sets name of PV
  labels:
    project: web-watcher
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany # Sets read and write access
  resources:
    requests:
      storage: 1Mi # Sets volume size
  volumeName: web-watcher.config-volume
