// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/htchan/WebHistory/internal/repository (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=../mock/repository/repository.go -package=mockrepo . Repository
//

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	model "github.com/htchan/WebHistory/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateUserWebsite mocks base method.
func (m *MockRepository) CreateUserWebsite(arg0 context.Context, arg1 *model.UserWebsite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserWebsite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserWebsite indicates an expected call of CreateUserWebsite.
func (mr *MockRepositoryMockRecorder) CreateUserWebsite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserWebsite", reflect.TypeOf((*MockRepository)(nil).CreateUserWebsite), arg0, arg1)
}

// CreateWebsite mocks base method.
func (m *MockRepository) CreateWebsite(arg0 context.Context, arg1 *model.Website) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebsite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWebsite indicates an expected call of CreateWebsite.
func (mr *MockRepositoryMockRecorder) CreateWebsite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebsite", reflect.TypeOf((*MockRepository)(nil).CreateWebsite), arg0, arg1)
}

// DeleteUserWebsite mocks base method.
func (m *MockRepository) DeleteUserWebsite(arg0 context.Context, arg1 *model.UserWebsite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserWebsite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserWebsite indicates an expected call of DeleteUserWebsite.
func (mr *MockRepositoryMockRecorder) DeleteUserWebsite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserWebsite", reflect.TypeOf((*MockRepository)(nil).DeleteUserWebsite), arg0, arg1)
}

// DeleteWebsite mocks base method.
func (m *MockRepository) DeleteWebsite(arg0 context.Context, arg1 *model.Website) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWebsite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWebsite indicates an expected call of DeleteWebsite.
func (mr *MockRepositoryMockRecorder) DeleteWebsite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWebsite", reflect.TypeOf((*MockRepository)(nil).DeleteWebsite), arg0, arg1)
}

// FindUserWebsite mocks base method.
func (m *MockRepository) FindUserWebsite(ctx context.Context, userUUID, websiteUUID string) (*model.UserWebsite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserWebsite", ctx, userUUID, websiteUUID)
	ret0, _ := ret[0].(*model.UserWebsite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserWebsite indicates an expected call of FindUserWebsite.
func (mr *MockRepositoryMockRecorder) FindUserWebsite(ctx, userUUID, websiteUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserWebsite", reflect.TypeOf((*MockRepository)(nil).FindUserWebsite), ctx, userUUID, websiteUUID)
}

// FindUserWebsites mocks base method.
func (m *MockRepository) FindUserWebsites(ctx context.Context, userUUID string) (model.UserWebsites, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserWebsites", ctx, userUUID)
	ret0, _ := ret[0].(model.UserWebsites)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserWebsites indicates an expected call of FindUserWebsites.
func (mr *MockRepositoryMockRecorder) FindUserWebsites(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserWebsites", reflect.TypeOf((*MockRepository)(nil).FindUserWebsites), ctx, userUUID)
}

// FindUserWebsitesByGroup mocks base method.
func (m *MockRepository) FindUserWebsitesByGroup(ctx context.Context, userUUID, group string) (model.WebsiteGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserWebsitesByGroup", ctx, userUUID, group)
	ret0, _ := ret[0].(model.WebsiteGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserWebsitesByGroup indicates an expected call of FindUserWebsitesByGroup.
func (mr *MockRepositoryMockRecorder) FindUserWebsitesByGroup(ctx, userUUID, group any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserWebsitesByGroup", reflect.TypeOf((*MockRepository)(nil).FindUserWebsitesByGroup), ctx, userUUID, group)
}

// FindWebsite mocks base method.
func (m *MockRepository) FindWebsite(ctx context.Context, uuid string) (*model.Website, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWebsite", ctx, uuid)
	ret0, _ := ret[0].(*model.Website)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWebsite indicates an expected call of FindWebsite.
func (mr *MockRepositoryMockRecorder) FindWebsite(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWebsite", reflect.TypeOf((*MockRepository)(nil).FindWebsite), ctx, uuid)
}

// FindWebsites mocks base method.
func (m *MockRepository) FindWebsites(arg0 context.Context) ([]model.Website, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWebsites", arg0)
	ret0, _ := ret[0].([]model.Website)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWebsites indicates an expected call of FindWebsites.
func (mr *MockRepositoryMockRecorder) FindWebsites(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWebsites", reflect.TypeOf((*MockRepository)(nil).FindWebsites), arg0)
}

// Stats mocks base method.
func (m *MockRepository) Stats() sql.DBStats {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats")
	ret0, _ := ret[0].(sql.DBStats)
	return ret0
}

// Stats indicates an expected call of Stats.
func (mr *MockRepositoryMockRecorder) Stats() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockRepository)(nil).Stats))
}

// UpdateUserWebsite mocks base method.
func (m *MockRepository) UpdateUserWebsite(arg0 context.Context, arg1 *model.UserWebsite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserWebsite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserWebsite indicates an expected call of UpdateUserWebsite.
func (mr *MockRepositoryMockRecorder) UpdateUserWebsite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserWebsite", reflect.TypeOf((*MockRepository)(nil).UpdateUserWebsite), arg0, arg1)
}

// UpdateWebsite mocks base method.
func (m *MockRepository) UpdateWebsite(arg0 context.Context, arg1 *model.Website) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWebsite", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWebsite indicates an expected call of UpdateWebsite.
func (mr *MockRepositoryMockRecorder) UpdateWebsite(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWebsite", reflect.TypeOf((*MockRepository)(nil).UpdateWebsite), arg0, arg1)
}
