apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-history-backedn-ingress
spec:
  rules:
  - host: web-history.raspi.home
    http:
      paths:
      - pathType: Prefix
        path: /api/
        backend:
          service:
            name: web-history-backend-service
            port:
              number: 8000
