apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-history.api  # Sets Deployment name
  labels:
    app: api
    project: web-history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      project: web-history
  template:
    metadata:
      labels:
        app: api
        project: web-history
    spec:
      containers:
        - name: web-history-api
          image: ghcr.io/htchan/web-history-api:latest # Sets Image
          imagePullPolicy: "IfNotPresent"
          resources:
            limits:
              memory: 50M
            requests:
              memory: 5M
          envFrom:
            - secretRef:
                name: web-history.api.secret
          volumeMounts:
            - mountPath: /config
              name: web-history-config-volume
            - mountPath: /migrations
              name: web-history-migrations-volume
      volumes:
        - name: web-history-config-volume
          persistentVolumeClaim:
            claimName: web-history.config-claim
        - name: web-history-migrations-volume
          persistentVolumeClaim:
            claimName: web-history.migrations-claim
      restartPolicy: Always
