apiVersion: v1
kind: Service
metadata:
  name: web-history-api-service
  labels:
    app: api
    project: web-history
spec:
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  selector:
    app: api
    project: web-history

