kind: PersistentVolume
apiVersion: v1
metadata:
  name: web-history.worker.config-volume
  labels:
    label: local
    app: worker
    project: web-history
spec:
  storageClassName: manual
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /volumes/web-history-worker-data/config
