apiVersion: batch/v1
kind: CronJob
metadata:
  name: web-history.website-batch-update-cronjob
  labels:
    app: worker
    project: web-history
spec:
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  schedule: '0 4 * * 5'  # runs every minute
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
          - name: redis-cli
            image: redis:alpine
            command: ["redis-cli"]
            args:
            - "-h"
            - "common-infra-redis-service"
            - "-p"
            - "6379"
            - "XADD"
            - "web-history/website-batch-update"
            - "*"
            - "date"
            - "$(date +%Y-%m-%d)"
          restartPolicy: Never

