name: BE Testing
run-name: ${{github.actor}} trigger tests for BE
on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
      - 'internal/**'
      - 'cmd/**'
      - 'data/testing/**'
      - 'database/**'
      - 'build/**'
      - 'Makefile'
      - 'go.*'
      - '.github/workflows/backend-test.yml'
  push:
    branches:
      - master
    paths:
      - 'internal/**'
      - 'cmd/**'
      - 'data/testing/**'
      - 'database/**'
      - 'build/**'
      - 'Makefile'
      - 'go.*'
      - '.github/workflows/backend-test.yml'

jobs:
  Execute-Backend-Testcase:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Golang environment
        uses: actions/setup-go@v4
        with: 
          go-version: 1.21
          cache: true
          cache-dependency-path: |
            go.sum
            go.mod
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Test
        working-directory: "."
        run: make test
