name: run testfor BE
run-name: ${{github.actor}} is running testcase for BE
on: 
  workflow_dispatch:

  pull_request:
    branches:
      - master
    paths:
      - 'backend/**'
      - '.github/workflows/backend-test.yml'

jobs:
  Execute-Backend-Testcase:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Golang environment
        uses: actions/setup-go@v3
        with: 
          go-version: 1.19
          cache: true
          cache-dependency-path: |
            **/go.sum
            **/go.mod
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Test
        working-directory: ./backend
        run: make test
