name: run testfor BE
run-name: ${{github.actor}} is running testcase for BE
on: workflow_dispatch
jobs:
  Execute-Backend-Testcase:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Go to backend directory
        run: cd ${{ github.workspace }}/backend
      - name: Set up Golang environment
        uses: actions/setup-go@v3
        with: 
          go-version: 1.19
      - name: Test
        run: go test -v ./...
